//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkManagement2.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_template
    {
        public int id { get; set; }
        public string tamplate_body { get; set; }
        public string template_name { get; set; }
    }
}
